services:
  base:
    build:
      context: .
      args:
        - username=${USER}

    stdin_open: true
    tty: true
    shm_size: '2gb'  # Changing --shm-size on docker-run is recommended (with enough RAM)

    environment:
      - PULSE_SERVER=unix:/var/tmp/pulseaudio.socket
      - XAUTHORITY=/home/${USER}/.Xauthority
      - DISPLAY=${DISPLAY}

    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:/var/tmp/pulseaudio.socket
      - ${XAUTHORITY}:/var/tmp/Xauthority:ro  # TODO: ${XAUTHORITY} could change across reboots
      - /etc/hostname:/var/tmp/hostname:ro

    devices:
      - /dev/dri:/dev/dri  # See https://github.com/mviereck/x11docker/wiki/Hardware-acceleration
      - /dev/kvm:/dev/kvm

    command: >
      bash -c "
        if [ ! -e /var/tmp/initialized ]; then
          uid=$$(stat -c '%u' /var/tmp/Xauthority) &&
          gid=$$(stat -c '%g' /var/tmp/Xauthority) &&
          groupmod -g $$gid ${USER} &&
          usermod -u $$uid -g $$gid ${USER} >/dev/null &&
          skel=$$(mktemp -d) &&
          cp -r /etc/skel/. $$skel &&
          chown -R $$uid:$$gid $$skel &&
          cp -rp --update=none $$skel/. /home/${USER} &&
          touch /var/tmp/initialized &&
          unset uid gid skel;
        fi &&
        cp -p /var/tmp/Xauthority $$XAUTHORITY &&
        host=$$(cat /var/tmp/hostname) &&
        display=$$(grep -o ':\\([0-9\\.]\\+\\)$$' <<< \"$DISPLAY\") &&
        auths=$$(xauth list | grep \"$$host\") &&
        auth=$$(
          ((grep \"$$display\" <<< \"$$auths\") || (grep ': ' <<< \"$$auths\")) \\
            | head -n 1 \\
            | sed -E \"s/^[^/:]+/$$HOSTNAME/; s/: /$$display /\"
        ) &&
        su ${USER} -c \"xauth add $$auth\" &&
        unset host display auths auth &&
        exec su -lw PULSE_SERVER,XAUTHORITY,DISPLAY ${USER}
      "
