services:
  bookwormify:
    image: debian:bookworm

    environment:
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - XAUTHORITY=/tmp/.Xauthority
      - DISPLAY=${DISPLAY}

    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:/tmp/pulseaudio.socket
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix

    devices:
      - /dev/dri:/dev/dri  # See https://github.com/mviereck/x11docker/wiki/Hardware-acceleration

    # NOTE: Unless $HOSTNAME exists this might break if xauth contains auths with the same $DISPLAY
    command: >
      bash -c "
        if [ ! -e /root/setup ]; then
          apt update -y &&
          apt install -y udev xauth sudo mesa-utils{,-extra} mplayer firefox-esr &&
          uid=$$(stat -c '%u' /root/.Xauthority) &&
          gid=$$(stat -c '%g' /root/.Xauthority) &&
          groupadd -g $$gid ${USER} &&
          useradd -mG sudo,video,render -u $$uid -g $$gid -s /bin/bash ${USER} &&
          sed -i 's/\\(%sudo.*\\)ALL$$/\\1NOPASSWD: ALL/' /etc/sudoers &&
          touch /root/setup &&
          unset uid gid;
        fi &&
        cp -p /root/.Xauthority /tmp/.Xauthority &&
        auth=$$(xauth list | grep '${HOSTNAME}' | grep '${DISPLAY}' | head -n 1) &&
        template=$$(echo $$auth | sed -E 's/^[^ \\/]+//') &&
        printf 'add %s%s\\n' \"$$HOSTNAME\" \"$$template\" | su ${USER} -c xauth &&
        unset auth template &&
        exec su -lw PULSE_SERVER,XAUTHORITY,DISPLAY ale
      "
