services:
  base:
    build:
      context: .
      args:
        - username=${USER}

    stdin_open: true
    tty: true
    shm_size: '2gb'  # Changing --shm-size on docker-run is recommended (with enough RAM)

    environment:
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - XAUTHORITY=/tmp/.Xauthority
      - DISPLAY=${DISPLAY}

    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:/tmp/pulseaudio.socket
      - ${XAUTHORITY}:/root/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/hostname:/tmp/host-hostname:ro

    devices:
      - /dev/dri:/dev/dri  # See https://github.com/mviereck/x11docker/wiki/Hardware-acceleration
      - /dev/kvm:/dev/kvm

    command: >
      bash -c "
        if [ ! -e /root/setup ]; then
          uid=$$(stat -c '%u' /root/.Xauthority) &&
          gid=$$(stat -c '%g' /root/.Xauthority) &&
          groupmod -g $$gid ${USER} &&
          usermod -u $$uid -g $$gid ${USER} >/dev/null &&
          skel=$$(mktemp -d) &&
          cp -r /etc/skel/. $$skel &&
          chown -R $$uid:$$gid $$skel &&
          cp -rnp $$skel/. /home/${USER} &&
          touch /root/setup &&
          unset uid gid skel;
        fi &&
        cp -p /root/.Xauthority /tmp/.Xauthority &&
        host=$$(cat /tmp/host-hostname) &&
        display=$$(grep -o ':\\([0-9\\.]\\+\\)$$' <<< \"$DISPLAY\") &&
        auths=$$(xauth list | grep \"$$host\") &&
        auth=$$(
          ((grep \"$$display\" <<< \"$$auths\") || (grep ': ' <<< \"$$auths\")) \\
            | head -n 1 \\
            | sed -E \"s/^[^/:]+/$$HOSTNAME/; s/: /$$display /\"
        ) &&
        su ${USER} -c \"xauth add $$auth\" &&
        unset host display auths auth &&
        exec su -lw PULSE_SERVER,XAUTHORITY,DISPLAY ${USER}
      "
